name: pcgan
channels:
  - conda-forge
  - pytorch
  - pytorch3d
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pytorch::pytorch=1.9.0
  - plotly=5.5.0
  - wandb
  - gdown=3.8.3
  - black
  - pytorch3d
